# Si TON SITE est à https://ouaisfieu.github.io/magasin/
url: "https://ouaisfieu.github.io"   # ⚠️ sans /magasin
baseurl: "/magasin"                  # ⚠️ avec le slash initial

title: "ouaisfi·eu"
description: "Magasin de fichiers, scripts et ressources à télécharger"
default_image: "/assets/og-default.jpg"

# Active Minimal Mistakes sans Gemfile
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "dark"         # (dark, default, air, aqua, neon, etc.)

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-include-cache

# Image OG par défaut
defaults:
  - scope:
      path: "o"
      type: "pages"
    values:
      layout: "single"      # layout Minimal Mistakes
      share: true           # boutons de partage
      author_profile: false
      read_time: false
      toc: false

permalink: /:path/:basename/   # propre pour pages
