# Si TON SITE est à https://ouaisfieu.github.io/magasin/
url: "https://ouaisfieu.github.io"   # ⚠️ sans /magasin
baseurl: "/magasin"                  # ⚠️ avec le slash initial

title: "ouaisfi·eu"
description: "Magasin de fichiers, scripts et ressources à télécharger"
default_image: "/assets/og-default.jpg"

markdown: kramdown
theme: minima

plugins:
  - jekyll-seo-tag

# Applique le layout par défaut aux pages de o/
defaults:
  - scope:
      path: "o"
    values:
      layout: "default"
