title: "ouaisfi·eu"
description: "Magasin de fichiers, scripts et ressources à télécharger"
baseurl: "/magasin" # vide si ton site est à la racine
url: "https://ouaisfieu.github.io/magasin" # adapte à ton repo Pages
default_image: "/assets/og-default.jpg"

markdown: kramdown
theme: minima

plugins:
  - jekyll-seo-tag

defaults:
  - scope:
      path: "o"
      type: "pages"
    values:
      layout: "default"
      css: "/assets/css/custom.css"

include:
  - assets
  - o

exclude:
  - convert_manifest_to_md.py
  - README.md
